theme                       : jekyll-theme-slate
name                        : 0xRF
title                       : The Thought Hole
description                 : For when I feel like writing stuff down
url:                        : https://demonbeaver.github.io
