# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: demonbeaver # jekyll-seo-tag > Owners twitter username
author: demonbeaver # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Ron Freudenthal # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/demonbeaver
    - https://www.linkedin.com/in/ron-freudenthal-47466b76/
    - https://github.com/demonbeaver
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Jerusalem # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Writeups for crackmes/CTFs, updates and independent research" # The post list page content
    feature_text: |
      I wrote this
    feature_image: "/assets/feature_images/background.jpg" # https://picsum.photos/id/1022/2560/600

collections_dir: collections

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "The Thought Hole" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/android-chrome-512x512.png" # Site logo, also used in jekyll-seo-tag
description: "@demonbeaver's homepage" # Site description and default description, also used in jekyll-seo-tag
url: "https://demonbeaver.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/demonbeaver/demonbeaver.github.io"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  48: '/assets/logos/favicon.ico'
  180: '/assets/logos/apple-touch-icon.png'
  192: '/assets/logos/android-chrome-192x192.png'
  512: '/assets/logos/android-chrome-512x512.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
# - title: Elements
#   url: /elements/
- title: Posts
  url: /blog/
# - title: Research
#   url: /publications/
- title: About Me
  url: https://www.youtube.com/watch?v=oHg5SJYRHA0
# - title: Categories
#   url: /categories/
# - title: Search
#   url: /search/
# - title: Fork Alembic
#   url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: Based on the Alembic Theme by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/demonbeaver
  LinkedIn: https://www.linkedin.com/in/ron-freudenthal-47466b76/
  GitHub: https://github.com/demonbeaver
  link: https://demonbeaver.github.io
  #RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
